@extends('layouts.app')

@section('title', 'MyCart | Everyday shopping, made easy')

@section('content')
@php
    $catalogImages = [
        'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=900&q=85',
        'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=900&q=85',
        'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=85',
        'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=900&q=85',
        'https://images.unsplash.com/photo-1556228578-8c89e6adf883?auto=format&fit=crop&w=900&q=85',
        'https://images.unsplash.com/photo-1523381210434-271e8be1f52b?auto=format&fit=crop&w=900&q=85',
    ];
    $fallbackProducts = collect([
        ['name'=>'Wireless noise-canceling headphones', 'price'=>360, 'image'=>$catalogImages[0], 'category'=>'Electronics'],
        ['name'=>'Modern everyday wrist watch', 'price'=>145, 'image'=>$catalogImages[1], 'category'=>'Accessories'],
        ['name'=>'Lightweight running sneakers', 'price'=>190, 'image'=>$catalogImages[2], 'category'=>'Fashion'],
        ['name'=>'Smartphone with brilliant display', 'price'=>590, 'image'=>$catalogImages[3], 'category'=>'Digital'],
        ['name'=>'Daily glow skincare set', 'price'=>99, 'image'=>$catalogImages[4], 'category'=>'Beauty'],
    ]);
    $products = $featured->count() ? $featured : $fallbackProducts;
    $categoryVisuals = [
        ['name'=>'Fashion', 'image'=>'https://images.unsplash.com/photo-1445205170230-053b83016050?auto=format&fit=crop&w=900&q=85', 'offer'=>'Up to 40% off'],
        ['name'=>'Electronics', 'image'=>'https://images.unsplash.com/photo-1498049794561-7780e7231661?auto=format&fit=crop&w=900&q=85', 'offer'=>'New arrivals'],
        ['name'=>'Home & living', 'image'=>'https://images.unsplash.com/photo-1618220179428-22790b461013?auto=format&fit=crop&w=900&q=85', 'offer'=>'Up to 35% off'],
        ['name'=>'Beauty', 'image'=>'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?auto=format&fit=crop&w=900&q=85', 'offer'=>'Beauty edit'],
    ];
    $productLoop = $products->concat($products)->concat($products);
@endphp

<div class="store-shell overflow-hidden">
<section class="mx-auto max-w-[1320px] px-4 pt-5 sm:px-6">
    <div class="grid gap-5 lg:grid-cols-[255px_minmax(0,1fr)]">
        <aside class="hidden rounded-sm border border-slate-100 bg-white py-2 lg:block">
            <p class="px-5 py-3 text-xs font-bold uppercase tracking-[.14em] text-slate-400">Shop categories</p>
            @forelse($categories as $category)<a href="{{ route('products.category', $category->slug) }}" class="flex items-center justify-between px-5 py-3 text-sm text-slate-700 hover:bg-[#f4f8ff] hover:text-[#1677ff]"><span>{{ $category->name }}</span><span class="text-slate-300">›</span></a>@empty
                @foreach(['Fashion & Accessories','Digital & Electronics','Home & Living','Health & Beauty','Sports & Outdoor','Travel essentials','Tools & equipment'] as $category)<a href="{{ route('products.index') }}" class="flex items-center justify-between px-5 py-3 text-sm text-slate-700 hover:bg-[#f4f8ff] hover:text-[#1677ff]"><span>{{ $category }}</span><span class="text-slate-300">›</span></a>@endforeach
            @endforelse
        </aside>

        <div class="relative isolate min-h-[470px] overflow-hidden rounded-sm bg-[#e9f3ff] shadow-[0_25px_70px_rgba(30,64,175,.16)] sm:min-h-[540px]" data-store-slider>
            <article class="store-slide is-active absolute inset-0 overflow-hidden bg-[radial-gradient(circle_at_72%_42%,#b8ddff,transparent_20%),linear-gradient(120deg,#f4faff_5%,#bfddff_47%,#5a91df_100%)]" data-store-slide>
                <div class="absolute right-[7%] top-[12%] h-[76%] w-[39%] rounded-[48%] bg-white/20 blur-2xl"></div><img src="https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=1300&q=90" alt="Featured smartphone" class="store-slide-image absolute bottom-0 right-[5%] h-[77%] w-[44%] object-contain object-bottom drop-shadow-2xl sm:h-[88%]">
                <div class="store-slide-copy relative z-10 flex min-h-[470px] max-w-[60%] flex-col justify-center px-6 py-12 sm:min-h-[540px] sm:px-12"><p class="text-[10px] font-extrabold uppercase tracking-[.22em] text-[#1677ff]">Introducing new</p><h1 class="mt-4 text-3xl font-extrabold leading-[1.05] text-slate-900 sm:text-5xl">Everything tech,<br><span class="text-[#1677ff]">made for you.</span></h1><p class="mt-5 hidden max-w-sm text-sm leading-6 text-slate-600 sm:block">Discover smart essentials with everyday value, fast delivery and a simple checkout experience.</p><a href="{{ route('products.index') }}" class="mt-7 inline-flex w-fit items-center gap-2 rounded-sm bg-[#1677ff] px-5 py-3 text-sm font-bold text-white shadow-lg shadow-blue-200 transition hover:-translate-y-0.5 hover:bg-[#0864e0]">Shop now <span>→</span></a><p class="mt-6 text-sm font-bold text-slate-700">Starting from <span class="text-xl text-[#1677ff]">$59</span></p></div>
            </article>
            <article class="store-slide absolute inset-0 overflow-hidden bg-[radial-gradient(circle_at_68%_30%,#fde2ab,transparent_19%),linear-gradient(120deg,#fff9ed_5%,#ffe0a5_48%,#e8973c_100%)]" data-store-slide>
                <div class="absolute -right-16 top-4 h-[110%] w-[55%] rounded-full bg-white/20 blur-3xl"></div><img src="https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=1300&q=90" alt="Premium headphones" class="store-slide-image absolute bottom-0 right-[5%] h-[76%] w-[47%] object-contain object-bottom drop-shadow-2xl sm:h-[88%]">
                <div class="store-slide-copy relative z-10 flex min-h-[470px] max-w-[60%] flex-col justify-center px-6 py-12 sm:min-h-[540px] sm:px-12"><p class="text-[10px] font-extrabold uppercase tracking-[.22em] text-[#ab5a00]">Sound, redefined</p><h2 class="mt-4 text-3xl font-extrabold leading-[1.05] text-slate-900 sm:text-5xl">Hear every detail.<br><span class="text-[#d87d13]">Feel every beat.</span></h2><p class="mt-5 hidden max-w-sm text-sm leading-6 text-slate-600 sm:block">Elevate work, travel and downtime with the audio edit everyone is talking about.</p><a href="{{ route('products.index') }}" class="mt-7 inline-flex w-fit items-center gap-2 rounded-sm bg-slate-900 px-5 py-3 text-sm font-bold text-white shadow-lg transition hover:-translate-y-0.5">Explore audio <span>→</span></a><p class="mt-6 text-sm font-bold text-slate-700">Save up to <span class="text-xl text-[#d87d13]">40%</span></p></div>
            </article>
            <article class="store-slide absolute inset-0 overflow-hidden bg-[radial-gradient(circle_at_73%_38%,#d6f7c7,transparent_18%),linear-gradient(120deg,#f5fff0_5%,#c9edbd_48%,#5ca466_100%)]" data-store-slide>
                <div class="absolute right-[10%] top-[9%] h-[72%] w-[38%] rounded-full border-[24px] border-white/20"></div><img src="https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=1300&q=90" alt="New season sneakers" class="store-slide-image absolute bottom-0 right-[5%] h-[77%] w-[45%] object-contain object-bottom drop-shadow-2xl sm:h-[89%]">
                <div class="store-slide-copy relative z-10 flex min-h-[470px] max-w-[60%] flex-col justify-center px-6 py-12 sm:min-h-[540px] sm:px-12"><p class="text-[10px] font-extrabold uppercase tracking-[.22em] text-[#397746]">New season edit</p><h2 class="mt-4 text-3xl font-extrabold leading-[1.05] text-slate-900 sm:text-5xl">Move with<br><span class="text-[#40804c]">new energy.</span></h2><p class="mt-5 hidden max-w-sm text-sm leading-6 text-slate-600 sm:block">Fresh fits, everyday sneakers and active essentials selected for your next move.</p><a href="{{ route('products.index') }}" class="mt-7 inline-flex w-fit items-center gap-2 rounded-sm bg-[#31713e] px-5 py-3 text-sm font-bold text-white shadow-lg transition hover:-translate-y-0.5">Shop fashion <span>→</span></a><p class="mt-6 text-sm font-bold text-slate-700">New styles from <span class="text-xl text-[#40804c]">$29</span></p></div>
            </article>
            <div class="absolute bottom-6 left-6 z-20 flex gap-2 sm:left-12"><button class="store-slider-dot is-active" aria-label="Show tech collection" data-store-dot></button><button class="store-slider-dot" aria-label="Show audio collection" data-store-dot></button><button class="store-slider-dot" aria-label="Show fashion collection" data-store-dot></button></div>
        </div>
    </div>
</section>

<section class="mx-auto max-w-[1320px] px-4 py-12 sm:px-6" data-reveal><div class="grid grid-cols-2 gap-3 sm:grid-cols-4 sm:gap-5"><div class="flex items-center gap-3 border-r border-slate-100 pr-2"><span class="grid h-11 w-11 place-items-center rounded-full bg-[#edf6ff] text-xl">🚚</span><div><h2 class="text-sm font-bold">Fast delivery</h2><p class="mt-0.5 text-xs text-slate-500">Delivery in 24 hours</p></div></div><div class="flex items-center gap-3 border-r border-slate-100 pr-2"><span class="grid h-11 w-11 place-items-center rounded-full bg-[#fff4e5] text-xl">↩</span><div><h2 class="text-sm font-bold">Easy returns</h2><p class="mt-0.5 text-xs text-slate-500">Money-back guarantee</p></div></div><div class="flex items-center gap-3 border-r border-slate-100 pr-2"><span class="grid h-11 w-11 place-items-center rounded-full bg-[#eff9ed] text-xl">▣</span><div><h2 class="text-sm font-bold">Secure payment</h2><p class="mt-0.5 text-xs text-slate-500">Your money is safe</p></div></div><div class="flex items-center gap-3"><span class="grid h-11 w-11 place-items-center rounded-full bg-[#f3efff] text-xl">◌</span><div><h2 class="text-sm font-bold">Support 24/7</h2><p class="mt-0.5 text-xs text-slate-500">Live chat & help</p></div></div></div></section>

<section class="bg-[#f7f9fc] py-16"><div class="mx-auto max-w-[1320px] px-4 sm:px-6" data-reveal><div class="mb-7 flex items-end justify-between"><div><p class="text-xs font-bold uppercase tracking-[.16em] text-[#1677ff]">Hot right now</p><h2 class="mt-2 text-2xl font-extrabold text-slate-900 sm:text-3xl">Flash sale</h2></div><div class="hidden items-center gap-2 text-sm sm:flex"><span class="text-slate-500">Deals end in</span><b class="rounded bg-slate-900 px-2 py-1 text-white">08</b><b class="rounded bg-slate-900 px-2 py-1 text-white">42</b><b class="rounded bg-slate-900 px-2 py-1 text-white">18</b></div><a href="{{ route('products.index') }}" class="text-sm font-bold text-[#1677ff]">View all →</a></div><div class="grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-5">
        @foreach($products->take(5) as $index => $product)
            @php($productImage = data_get($product, 'image') ?: $catalogImages[$index % count($catalogImages)]) @php($productName = data_get($product, 'name')) @php($price = data_get($product, 'sale_price') ?: data_get($product, 'price')) @php($productLink = data_get($product, 'slug') ? route('products.show', $product->slug) : route('products.index'))
            <article class="group relative overflow-hidden rounded-sm bg-white p-3 shadow-sm transition hover:-translate-y-1 hover:shadow-lg"><a href="{{ $productLink }}" class="block"><div class="relative aspect-square overflow-hidden bg-slate-50"><img src="{{ $productImage }}" alt="{{ $productName }}" class="h-full w-full object-cover transition duration-500 group-hover:scale-105"><span class="absolute left-2 top-2 rounded-sm bg-[#ff5d3d] px-2 py-1 text-[10px] font-bold text-white">-{{ 15 + $index * 5 }}%</span></div><p class="mt-3 text-[10px] font-bold uppercase tracking-wide text-[#1677ff]">Best deal</p><h3 class="mt-1 line-clamp-2 min-h-10 text-sm font-semibold leading-5 text-slate-800">{{ $productName }}</h3><div class="mt-2 flex items-baseline gap-2"><strong class="text-base text-[#1677ff]">${{ number_format((float)$price, 0) }}</strong><s class="text-xs text-slate-400">${{ number_format((float)$price * 1.25, 0) }}</s></div></a></article>
        @endforeach
    </div></div></section>

<section class="mx-auto max-w-[1320px] px-4 py-16 sm:px-6" data-reveal><div class="mb-7 flex items-end justify-between"><div><p class="text-xs font-bold uppercase tracking-[.16em] text-[#1677ff]">Browse collections</p><h2 class="mt-2 text-2xl font-extrabold text-slate-900 sm:text-3xl">Shop popular categories</h2></div><a href="{{ route('products.index') }}" class="text-sm font-bold text-[#1677ff]">Explore all →</a></div><div class="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">@foreach($categoryVisuals as $category)<a href="{{ route('products.index') }}" class="group relative min-h-[260px] overflow-hidden rounded-sm bg-slate-900"><img src="{{ $category['image'] }}" alt="{{ $category['name'] }}" class="absolute inset-0 h-full w-full object-cover opacity-80 transition duration-500 group-hover:scale-105"><div class="absolute inset-0 bg-gradient-to-t from-slate-950/80 via-slate-900/10"></div><div class="absolute inset-x-5 bottom-5 text-white"><p class="text-xs font-semibold text-[#a9d2ff]">{{ $category['offer'] }}</p><h3 class="mt-1 text-xl font-extrabold">{{ $category['name'] }}</h3><span class="mt-3 inline-block text-sm font-bold">Shop now →</span></div></a>@endforeach</div></section>

<section class="bg-white py-16" data-reveal><div class="mx-auto max-w-[1320px] px-4 sm:px-6"><div class="mb-7 flex items-end justify-between"><div><p class="text-xs font-bold uppercase tracking-[.16em] text-[#1677ff]">Recommended for you</p><h2 class="mt-2 text-2xl font-extrabold text-slate-900 sm:text-3xl">Top sale products</h2></div><a href="{{ route('products.index') }}" class="text-sm font-bold text-[#1677ff]">Show all →</a></div><div class="product-rail gap-4 pb-4 sm:gap-5">@foreach($products->concat($products)->take(8) as $index => $product)@php($railImage = data_get($product, 'image') ?: $catalogImages[$index % count($catalogImages)]) @php($railName = data_get($product, 'name')) @php($railPrice = data_get($product, 'sale_price') ?: data_get($product, 'price'))<article class="group overflow-hidden rounded-sm border border-slate-100 bg-white p-3 shadow-sm transition hover:-translate-y-1 hover:shadow-xl"><div class="relative aspect-square overflow-hidden bg-slate-50"><img src="{{ $railImage }}" alt="{{ $railName }}" class="h-full w-full object-cover transition duration-500 group-hover:scale-105"><button class="absolute right-2 top-2 grid h-8 w-8 place-items-center rounded-full bg-white/90 text-sm text-slate-500 shadow">♡</button></div><p class="mt-3 text-[10px] font-bold uppercase tracking-[.13em] text-slate-400">{{ data_get($product, 'category.name') ?: data_get($product, 'category') ?: 'New arrival' }}</p><h3 class="mt-1 min-h-10 text-sm font-semibold leading-5 text-slate-800">{{ $railName }}</h3><div class="mt-3 flex items-center justify-between"><strong class="text-base text-[#1677ff]">${{ number_format((float)$railPrice, 0) }}</strong><a href="{{ route('products.index') }}" class="grid h-8 w-8 place-items-center rounded-sm bg-[#eef6ff] font-bold text-[#1677ff]">+</a></div></article>@endforeach</div></div></section>

<section class="mx-auto max-w-[1320px] px-4 py-16 sm:px-6" data-reveal><div class="grid gap-5 md:grid-cols-2"><a href="{{ route('products.index') }}" class="group relative min-h-[310px] overflow-hidden rounded-sm bg-[#152d58] p-8 text-white sm:p-11"><img src="https://images.unsplash.com/photo-1498049794561-7780e7231661?auto=format&fit=crop&w=1200&q=85" alt="Electronics sale" class="absolute inset-0 h-full w-full object-cover opacity-50 transition duration-700 group-hover:scale-105"><div class="absolute inset-0 bg-gradient-to-r from-[#10244a] via-[#10244a]/70 to-transparent"></div><div class="relative z-10 max-w-xs"><p class="text-[10px] font-bold uppercase tracking-[.2em] text-[#9ec8ff]">Digital & electronics</p><h2 class="mt-4 text-3xl font-extrabold leading-tight">Upgrade your everyday tech.</h2><p class="mt-3 text-sm leading-6 text-white/70">Smart picks, strong prices, and extra savings this week.</p><span class="mt-6 inline-block text-sm font-bold">Shop the edit →</span></div></a><a href="{{ route('products.index') }}" class="group relative min-h-[310px] overflow-hidden rounded-sm bg-[#6b4227] p-8 text-white sm:p-11"><img src="https://images.unsplash.com/photo-1445205170230-053b83016050?auto=format&fit=crop&w=1200&q=85" alt="Fashion sale" class="absolute inset-0 h-full w-full object-cover opacity-55 transition duration-700 group-hover:scale-105"><div class="absolute inset-0 bg-gradient-to-r from-[#59331c] via-[#59331c]/65 to-transparent"></div><div class="relative z-10 max-w-xs"><p class="text-[10px] font-bold uppercase tracking-[.2em] text-[#ffd8ae]">Style update</p><h2 class="mt-4 text-3xl font-extrabold leading-tight">Fresh looks, up to 40% off.</h2><p class="mt-3 text-sm leading-6 text-white/70">New-season clothes, shoes and accessories for every plan.</p><span class="mt-6 inline-block text-sm font-bold">Discover fashion →</span></div></a></div></section>

<section class="bg-[#101c33] py-20 text-white" data-reveal><div class="mx-auto grid max-w-[1320px] gap-10 px-4 sm:px-6 lg:grid-cols-[.85fr_1.15fr] lg:items-center"><div><p class="text-xs font-bold uppercase tracking-[.2em] text-[#7eb8ff]">Deal of the week</p><h2 class="mt-4 text-3xl font-extrabold leading-tight sm:text-5xl">Your next favourite find is waiting.</h2><p class="mt-5 max-w-md text-sm leading-7 text-slate-300">Explore hand-picked products with special pricing and everyday reliability. Limited offers refresh every week.</p><a href="{{ route('products.index') }}" class="mt-8 inline-flex rounded-sm bg-[#1677ff] px-6 py-3.5 text-sm font-bold text-white transition hover:-translate-y-0.5">See all deals →</a></div><div class="grid gap-4 sm:grid-cols-2"><div class="rounded-sm border border-white/10 bg-white/5 p-6 backdrop-blur"><span class="text-3xl">✦</span><h3 class="mt-5 text-lg font-bold">Curated quality</h3><p class="mt-2 text-sm leading-6 text-slate-400">Practical products selected for real life.</p></div><div class="rounded-sm border border-white/10 bg-white/5 p-6 backdrop-blur"><span class="text-3xl">◈</span><h3 class="mt-5 text-lg font-bold">Secure checkout</h3><p class="mt-2 text-sm leading-6 text-slate-400">Protected payments and simple order tracking.</p></div><div class="rounded-sm border border-white/10 bg-white/5 p-6 backdrop-blur"><span class="text-3xl">↗</span><h3 class="mt-5 text-lg font-bold">New drops</h3><p class="mt-2 text-sm leading-6 text-slate-400">Always something fresh to discover.</p></div><div class="rounded-sm border border-white/10 bg-white/5 p-6 backdrop-blur"><span class="text-3xl">✓</span><h3 class="mt-5 text-lg font-bold">Easy returns</h3><p class="mt-2 text-sm leading-6 text-slate-400">Shop with extra confidence every time.</p></div></div></div></section>

<section class="mx-auto max-w-[1320px] px-4 py-16 sm:px-6" data-reveal><div class="mb-7 flex items-end justify-between"><div><p class="text-xs font-bold uppercase tracking-[.16em] text-[#1677ff]">Shop more, save more</p><h2 class="mt-2 text-2xl font-extrabold text-slate-900 sm:text-3xl">Recommended items</h2></div><a href="{{ route('products.index') }}" class="text-sm font-bold text-[#1677ff]">Show all →</a></div><div class="grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-5">@foreach($productLoop->take(10) as $index => $item)@php($image = data_get($item,'image') ?: $catalogImages[$index % count($catalogImages)]) @php($name = data_get($item,'name')) @php($price = data_get($item,'sale_price') ?: data_get($item,'price'))<article class="group rounded-sm border border-slate-200 bg-white p-3 transition hover:-translate-y-1 hover:border-blue-200 hover:shadow-lg"><div class="relative aspect-square overflow-hidden bg-slate-50"><img src="{{ $image }}" alt="{{ $name }}" class="h-full w-full object-cover transition duration-500 group-hover:scale-105">@if($index % 3 === 0)<span class="absolute left-2 top-2 bg-[#1677ff] px-2 py-1 text-[9px] font-bold text-white">BEST DEAL</span>@endif</div><div class="mt-3 text-[#ff8a2a]">★★★★★ <span class="text-[10px] text-slate-400">(125)</span></div><h3 class="mt-1 min-h-10 text-sm font-semibold leading-5 text-slate-700">{{ $name }}</h3><strong class="mt-2 block text-base text-[#1677ff]">${{ number_format((float)$price,0) }}</strong></article>@endforeach</div></section>

<section class="mx-auto max-w-[1320px] px-4 pb-16 sm:px-6" data-reveal><div class="grid gap-5 md:grid-cols-[260px_1fr]"><aside class="relative min-h-[420px] overflow-hidden rounded-sm bg-[#102f55] p-7 text-white"><img src="https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=900&q=85" alt="Wireless earbuds" class="absolute bottom-0 left-0 h-[58%] w-full object-contain opacity-70"><div class="relative z-10"><p class="text-xs font-bold uppercase tracking-[.16em] text-[#8ec5ff]">Top sale product</p><h2 class="mt-5 text-3xl font-extrabold leading-tight">Wireless,<br>without limits.</h2><p class="mt-4 text-sm leading-6 text-slate-300">Premium sound for your work and play.</p><p class="mt-5 text-sm">Only for <b class="rounded bg-white px-2 py-1 text-slate-900">$299 USD</b></p></div><a href="{{ route('products.index') }}" class="absolute bottom-7 left-7 right-7 z-10 block bg-[#1677ff] py-3 text-center text-sm font-bold">Shop now →</a></aside><div><div class="mb-5 flex items-center justify-between"><div><p class="text-xs font-bold uppercase tracking-[.16em] text-[#1677ff]">Popular now</p><h2 class="mt-1 text-2xl font-extrabold">Top sale product</h2></div><a href="{{ route('products.index') }}" class="bg-slate-900 px-3 py-2 text-xs font-bold text-white">Show all</a></div><div class="grid grid-cols-2 overflow-hidden rounded-sm border border-slate-200 sm:grid-cols-3">@foreach($productLoop->take(9) as $index => $item)@php($image = data_get($item,'image') ?: $catalogImages[$index % count($catalogImages)]) @php($name = data_get($item,'name')) @php($price = data_get($item,'sale_price') ?: data_get($item,'price'))<a href="{{ route('products.index') }}" class="flex min-h-[125px] items-center gap-3 border-b border-r border-slate-200 bg-white p-3 transition hover:bg-[#f5f9ff]"><img src="{{ $image }}" alt="{{ $name }}" class="h-14 w-14 object-cover"><span><b class="line-clamp-2 text-xs leading-4 text-slate-700">{{ $name }}</b><i class="mt-1 block text-xs not-italic text-[#ff8a2a]">★★★★★ <small class="text-slate-400">(25)</small></i><strong class="mt-1 block text-[#1677ff]">${{ number_format((float)$price,0) }}</strong></span></a>@endforeach</div></div></div></section>

<section class="mx-auto max-w-[1320px] px-4 pb-16 sm:px-6" data-reveal><div class="grid gap-5 md:grid-cols-2"><a href="{{ route('products.index') }}" class="relative min-h-[245px] overflow-hidden rounded-sm bg-[#5ac9ec] p-8 text-white"><img src="https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=1100&q=85" alt="Women's collection" class="absolute inset-y-0 right-0 w-[48%] object-cover object-top"><div class="relative z-10 max-w-[52%]"><p class="text-xs font-bold uppercase tracking-[.18em]">Collection for girls</p><h2 class="mt-3 text-3xl font-extrabold">Fresh looks<br>for every day.</h2><p class="mt-3 font-bold">Up to <span class="text-yellow-200">40% off</span></p><span class="mt-5 inline-block rounded-full bg-white px-5 py-2 text-sm font-bold text-slate-800">Shop now</span></div></a><a href="{{ route('products.index') }}" class="relative min-h-[245px] overflow-hidden rounded-sm bg-[#ffca11] p-8 text-slate-900"><img src="https://images.unsplash.com/photo-1617137968427-85924c800a22?auto=format&fit=crop&w=1100&q=85" alt="Men's collection" class="absolute inset-y-0 right-0 w-[48%] object-cover object-top"><div class="relative z-10 max-w-[52%]"><p class="text-xs font-bold uppercase tracking-[.18em]">Collection for men</p><h2 class="mt-3 text-3xl font-extrabold">Built for<br>the weekend.</h2><p class="mt-3 font-bold">Up to <span class="text-white">40% off</span></p><span class="mt-5 inline-block rounded-full bg-white px-5 py-2 text-sm font-bold">Shop now</span></div></a></div></section>

<section class="bg-[#f0f4f9] py-16" data-reveal><div class="mx-auto max-w-[1320px] px-4 sm:px-6"><div class="mb-7 flex items-end justify-between"><div><p class="text-xs font-bold uppercase tracking-[.16em] text-[#1677ff]">Fresh categories</p><h2 class="mt-2 text-2xl font-extrabold text-slate-900 sm:text-3xl">Digital & electronics</h2></div><a href="{{ route('products.index') }}" class="text-sm font-bold text-[#1677ff]">Show all →</a></div><div class="grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-5">@foreach($productLoop->slice(3,5) as $index => $item)@php($image = data_get($item,'image') ?: $catalogImages[($index + 1) % count($catalogImages)]) @php($name = data_get($item,'name')) @php($price = data_get($item,'sale_price') ?: data_get($item,'price'))<article class="rounded-sm bg-white p-3 shadow-sm"><img src="{{ $image }}" alt="{{ $name }}" class="aspect-square w-full object-cover"><div class="mt-3 text-[#ff8a2a]">★★★★★ <small class="text-slate-400">(125)</small></div><h3 class="mt-1 min-h-10 text-sm font-semibold leading-5">{{ $name }}</h3><strong class="mt-2 block text-[#1677ff]">${{ number_format((float)$price,0) }}</strong></article>@endforeach</div></div></section>

<section class="mx-auto max-w-[1320px] px-4 py-16 sm:px-6" data-reveal><div class="grid overflow-hidden rounded-sm bg-[#dcecff] md:grid-cols-2"><div class="order-2 px-7 py-12 md:order-1 md:px-14 md:py-16"><p class="text-xs font-bold uppercase tracking-[.18em] text-[#1677ff]">Member offer</p><h2 class="mt-4 text-3xl font-extrabold leading-tight text-slate-900 sm:text-4xl">More value in every <span class="text-[#1677ff]">cart.</span></h2><p class="mt-4 max-w-md text-sm leading-6 text-slate-600">Create your account for order tracking, early deal access and a smooth checkout on every device.</p><a href="{{ route('register') }}" class="mt-7 inline-block rounded-sm bg-slate-900 px-5 py-3 text-sm font-bold text-white">Create free account →</a></div><div class="relative order-1 min-h-[290px] overflow-hidden md:order-2"><img src="https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=1200&q=85" alt="Easy checkout" class="absolute inset-0 h-full w-full object-cover"><div class="absolute inset-0 bg-[#1677ff]/15"></div></div></div></section>

<section class="mx-auto max-w-[1320px] px-4 pb-16 sm:px-6" data-reveal><div class="mb-7 flex items-end justify-between"><div><p class="text-xs font-bold uppercase tracking-[.16em] text-[#1677ff]">Trusted names</p><h2 class="mt-2 text-2xl font-extrabold text-slate-900 sm:text-3xl">Popular brands</h2></div><a href="{{ route('products.index') }}" class="text-sm font-bold text-[#1677ff]">Explore brands →</a></div><div class="grid grid-cols-2 overflow-hidden rounded-sm border border-slate-200 bg-white sm:grid-cols-3 lg:grid-cols-6">@foreach(['SONY','PUMA','SAMSUNG','adidas','MORPHE','FOSSIL','NIKON','LEGO','BOSE','LEVI’S','APPLE','TITAN'] as $brand)<a href="{{ route('products.index') }}" class="grid min-h-[130px] place-items-center border-b border-r border-slate-200 p-5 text-center transition hover:bg-[#f3f8ff]"><span class="text-lg font-extrabold tracking-tight text-slate-700">{{ $brand }}</span></a>@endforeach</div></section>

<section class="bg-[radial-gradient(circle_at_75%_20%,rgba(88,169,255,.4),transparent_26%),linear-gradient(110deg,#06245a,#0a55ba_52%,#1686ed)] py-14 text-white" data-reveal><div class="mx-auto flex max-w-[1000px] flex-col items-center gap-5 px-4 text-center sm:px-6"><p class="text-xs font-bold uppercase tracking-[.2em] text-blue-100">MyCart updates</p><h2 class="text-3xl font-extrabold sm:text-4xl">Get offers before they&apos;re gone.</h2><p class="max-w-lg text-sm leading-6 text-blue-100">Weekly deals, curated collections and new arrivals — straight to your inbox.</p><form class="flex w-full max-w-xl overflow-hidden rounded-sm bg-white p-1 shadow-xl"><input type="email" aria-label="Email address" placeholder="Enter your email address" class="min-w-0 flex-1 border-0 px-4 py-3 text-sm text-slate-800 focus:ring-0"><button class="bg-[#08111f] px-6 py-3 text-sm font-bold text-white">Subscribe</button></form></div></section>
</div>
@endsection
