<?php
namespace App\Filament\Resources\Coupons;
use App\Filament\Resources\Coupons\Pages\CreateCoupon; use App\Filament\Resources\Coupons\Pages\EditCoupon; use App\Filament\Resources\Coupons\Pages\ListCoupons; use App\Models\Coupon; use BackedEnum; use Filament\Forms\Components\DateTimePicker; use Filament\Forms\Components\Select; use Filament\Forms\Components\TextInput; use Filament\Forms\Components\Toggle; use Filament\Resources\Resource; use Filament\Schemas\Schema; use Filament\Support\Icons\Heroicon; use Filament\Tables\Columns\TextColumn; use Filament\Tables\Table;
class CouponResource extends Resource {
 protected static ?string $model=Coupon::class; protected static string|BackedEnum|null $navigationIcon=Heroicon::OutlinedTicket; protected static ?string $navigationLabel='Coupons'; protected static string|\UnitEnum|null $navigationGroup='Commerce'; protected static ?int $navigationSort=20;
 public static function form(Schema $schema): Schema{return $schema->components([TextInput::make('code')->required()->unique(ignoreRecord:true)->helperText('Saved automatically in uppercase.'),Select::make('type')->options(['percent'=>'Percentage','fixed'=>'Fixed amount'])->required(),TextInput::make('value')->numeric()->required(),TextInput::make('minimum_order')->numeric()->default(0),TextInput::make('usage_limit')->numeric()->nullable(),DateTimePicker::make('starts_at')->nullable(),DateTimePicker::make('expires_at')->nullable(),Toggle::make('is_active')->default(true)]);}
 public static function table(Table $table):Table{return $table->columns([TextColumn::make('code')->searchable()->weight('bold'),TextColumn::make('type')->badge(),TextColumn::make('value'),TextColumn::make('minimum_order')->money('INR'),TextColumn::make('uses')->label('Used'),TextColumn::make('usage_limit')->label('Limit'),TextColumn::make('expires_at')->dateTime(),TextColumn::make('is_active')->badge()->formatStateUsing(fn($v)=>$v?'Active':'Paused')->color(fn($v)=>$v?'success':'gray')])->recordActions([\Filament\Actions\EditAction::make()]);}
 public static function getPages():array{return ['index'=>ListCoupons::route('/'),'create'=>CreateCoupon::route('/create'),'edit'=>EditCoupon::route('/{record}/edit')];}
}
