@extends('layouts.app')
@section('title','Checkout · MyStore')
@section('content')
<section class="page-hero"><div class="container"><div class="breadcrumbs">MyStore / Checkout</div><h1>Checkout.</h1><p>Securely enter your delivery details. Your existing order flow remains unchanged.</p></div></section>
<section class="section"><div class="container"><div class="split"><div class="page-card"><div class="eyebrow">Delivery details</div><h2>Where should we send it?</h2>@if($errors->any())<div class="alert error">@foreach($errors->all() as $e)<div>{{ $e }}</div>@endforeach</div>@endif
<form class="form-grid" action="{{ route('checkout.store') }}" method="POST">@csrf
<div class="field full"><label>Coupon code</label><input name="coupon" value="{{ old('coupon', $couponCode ?? '') }}" placeholder="Enter coupon code"></div>
<div class="field"><label>Full name</label><input name="name" value="{{ old('name',auth()->user()->name) }}" required></div><div class="field"><label>Email</label><input type="email" name="email" value="{{ old('email',auth()->user()->email) }}" required></div><div class="field"><label>Phone</label><input name="phone" value="{{ old('phone') }}" required></div><div class="field"><label>ZIP code</label><input name="zip" value="{{ old('zip') }}" required></div><div class="field full"><label>Address</label><textarea name="address" required>{{ old('address') }}</textarea></div><div class="field"><label>City</label><input name="city" value="{{ old('city') }}" required></div><div class="field"><label>State</label><input name="state" value="{{ old('state') }}" required></div><div class="field full"><button class="btn btn-primary" style="min-height:52px">Place order · ${{ number_format($total,2) }}</button></div></form></div>
<div class="page-card" style="height:max-content"><div class="eyebrow">Summary</div><h2>Your selection.</h2>@foreach($cartItems as $item)<div style="display:flex;justify-content:space-between;padding:12px 0;border-bottom:1px solid var(--line);gap:12px"><span>{{ $item->product->name }} × {{ $item->quantity }}</span><strong>${{ number_format($item->product->price*$item->quantity,2) }}</strong></div>@endforeach<div style="display:grid;gap:10px;margin-top:18px"><div style="display:flex;justify-content:space-between"><span>Subtotal</span><span>${{ number_format($subtotal,2) }}</span></div><div style="display:flex;justify-content:space-between"><span>Shipping</span><span>${{ number_format($shipping,2) }}</span></div><div style="display:flex;justify-content:space-between;border-top:1px solid var(--line);padding-top:13px;font-size:18px"><strong>Total</strong><strong>${{ number_format($total,2) }}</strong></div></div></div></div></div></section>
<x-store-discovery-sections />
@endsection
