<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@yield('title', 'MyCart | Shop smarter')</title>
    @unless(request()->routeIs('home'))
        <link rel="stylesheet" href="{{ asset('premium.css') }}">
        <link rel="stylesheet" href="{{ asset('premium-redesign.css') }}">
    @endunless
    @vite(['resources/css/app.css', 'resources/js/app.js'])
</head>
<body class="bg-white font-sans text-slate-800 antialiased">
    @php($cartCount = auth()->check() ? \App\Models\CartItem::where('user_id', auth()->id())->sum('quantity') : 0)
    <div class="bg-[#050b14] text-[11px] text-slate-400"><div class="mx-auto flex max-w-[1320px] items-center justify-between px-4 py-2 sm:px-6"><p>Free delivery on eligible orders · Secure shopping every day</p><div class="hidden items-center gap-5 sm:flex"><a href="{{ route('contact') }}" class="hover:text-white">Help center</a><label class="flex items-center gap-2">Currency <select data-currency-select class="border-0 bg-transparent p-0 text-[11px] font-semibold text-white focus:ring-0"><option value="INR">INR ₹</option><option value="USD">USD $</option><option value="EUR">EUR €</option><option value="GBP">GBP £</option><option value="AED">AED د.إ</option></select></label></div></div></div>

    <header class="sticky top-0 z-50 border-b border-slate-700 bg-[#08111f] shadow-[0_8px_28px_rgba(15,23,42,.20)]" x-data="{ mobileOpen: false, categoryOpen: false }">
        <div class="mx-auto flex max-w-[1320px] items-center gap-3 px-4 py-4 sm:px-6 lg:gap-8">
            <button @click="mobileOpen = !mobileOpen" class="grid h-10 w-10 shrink-0 place-items-center rounded-lg border border-slate-600 text-white lg:hidden" aria-label="Open menu">☰</button>
            <a href="{{ route('home') }}" class="flex shrink-0 items-center gap-2 text-2xl font-extrabold tracking-tight text-[#4d9bff]">My<span class="text-white">cart</span><i class="h-2 w-2 rounded-full bg-[#ffb21a]"></i></a>
            <form action="{{ route('products.index') }}" method="GET" class="hidden flex-1 items-center overflow-hidden rounded-md border border-slate-200 bg-white lg:flex"><select name="category" class="h-12 w-40 border-0 border-r border-slate-200 bg-slate-50 text-sm text-slate-600 focus:ring-0"><option value="">All category</option>@foreach(\App\Models\Category::where('is_active', true)->orderBy('name')->get() as $headerCategory)<option value="{{ $headerCategory->id }}">{{ $headerCategory->name }}</option>@endforeach</select><input name="q" value="{{ request('q') }}" class="h-12 min-w-0 flex-1 border-0 text-sm focus:ring-0" placeholder="Search for products, brands and more"><button class="grid h-12 w-14 place-items-center bg-[#1677ff] text-xl text-white" aria-label="Search">⌕</button></form>
            <nav class="ml-auto flex items-center gap-3 text-sm text-slate-200 sm:gap-5"><a href="{{ auth()->check() ? route('dashboard') : route('login') }}" class="hidden items-center gap-2 md:flex"><span class="grid h-9 w-9 place-items-center rounded-full bg-white/10 text-base">♙</span><span class="hidden xl:block">{{ auth()->check() ? 'My account' : 'Sign in' }}</span></a><a href="{{ auth()->check() ? route('cart.index') : route('login') }}" class="relative flex items-center gap-2 font-semibold text-white"><span class="grid h-10 w-10 place-items-center rounded-full bg-[#1677ff] text-xl text-white">🛒</span><span class="hidden md:block">My cart</span>@if($cartCount)<b class="absolute -right-1 -top-1 grid h-5 min-w-5 place-items-center rounded-full bg-[#ffb21a] px-1 text-[10px] text-slate-900">{{ $cartCount }}</b>@endif</a></nav>
        </div>
        <form action="{{ route('products.index') }}" method="GET" class="mx-4 mb-4 flex overflow-hidden rounded-md border border-slate-600 bg-white lg:hidden"><input name="q" class="h-11 min-w-0 flex-1 border-0 text-sm focus:ring-0" placeholder="Search products"><button class="w-12 bg-[#1677ff] text-white">⌕</button></form>
        <div class="border-y border-slate-100 bg-white"><div class="mx-auto flex max-w-[1320px] items-center px-4 sm:px-6"><div class="group relative hidden lg:block"><button class="flex h-12 w-64 items-center justify-between bg-[#1677ff] px-5 text-sm font-bold text-white">All categories <span>⌄</span></button><div class="absolute left-0 top-full z-50 hidden w-64 border border-slate-100 bg-white p-3 shadow-[0_18px_32px_rgba(15,23,42,.16)] group-hover:block"><a href="{{ route('products.index') }}" class="block rounded p-2 text-sm font-semibold text-slate-700 hover:bg-[#f2f7ff] hover:text-[#1677ff]">All products</a>@foreach(\App\Models\Category::where('is_active', true)->orderBy('name')->get() as $headerCategory)<a href="{{ route('products.category', $headerCategory->slug) }}" class="flex items-center justify-between rounded p-2 text-sm text-slate-700 hover:bg-[#f2f7ff] hover:text-[#1677ff]">{{ $headerCategory->name }} <span class="text-slate-300">›</span></a>@endforeach</div></div><nav class="flex h-12 items-center gap-5 overflow-x-auto whitespace-nowrap px-1 text-sm font-semibold text-slate-700 sm:gap-7 lg:px-7"><a class="text-[#1677ff]" href="{{ route('home') }}">Home</a><a href="{{ route('products.index') }}">Shop</a><a href="{{ route('collections') }}">Collections</a><a href="{{ route('about') }}">About</a><a href="{{ route('blog') }}">Blog</a><a href="{{ route('contact') }}">Contact</a></nav></div></div>
        <div x-show="mobileOpen" x-transition class="border-t border-slate-700 bg-[#08111f] px-5 py-4 text-white lg:hidden"><nav class="grid gap-3 text-sm font-semibold"><a href="{{ route('home') }}">Home</a><a href="{{ route('products.index') }}">Shop</a><a href="{{ route('collections') }}">Collections</a><a href="{{ route('contact') }}">Contact</a></nav></div>
    </header>

    <main>@if(session('success'))<div class="mx-auto max-w-[1320px] px-4 pt-4 sm:px-6"><div class="rounded-md bg-emerald-50 px-4 py-3 text-sm text-emerald-700">{{ session('success') }}</div></div>@endif @if(session('error'))<div class="mx-auto max-w-[1320px] px-4 pt-4 sm:px-6"><div class="rounded-md bg-red-50 px-4 py-3 text-sm text-red-700">{{ session('error') }}</div></div>@endif @yield('content')</main>

    <footer class="{{ request()->routeIs('home') ? 'mt-0' : 'mt-16' }} bg-[#07111f] text-slate-300"><div class="mx-auto grid max-w-[1320px] gap-10 px-4 py-14 sm:grid-cols-2 sm:px-6 lg:grid-cols-[1.4fr_repeat(3,1fr)]"><div><a href="{{ route('home') }}" class="text-2xl font-extrabold text-white">My<span class="text-[#5ba0ff]">cart</span></a><p class="mt-4 max-w-xs text-sm leading-6 text-slate-400">Simple shopping for every day: quality products, easy checkout and dependable delivery.</p></div><div><h3 class="font-bold text-white">Shop</h3><div class="mt-4 grid gap-3 text-sm"><a href="{{ route('products.index') }}">All products</a><a href="{{ route('collections') }}">Top collections</a><a href="{{ route('products.index') }}">Best deals</a></div></div><div><h3 class="font-bold text-white">Customer care</h3><div class="mt-4 grid gap-3 text-sm"><a href="{{ route('contact') }}">Contact us</a><a href="{{ route('faq') }}">FAQs</a><a href="{{ route('shipping') }}">Shipping & delivery</a><a href="{{ route('returns') }}">Returns</a></div></div><div><h3 class="font-bold text-white">Secure shopping</h3><p class="mt-4 text-sm leading-6">Protected payments, simple returns and real human support.</p><div class="mt-5 flex gap-2"><span class="rounded bg-white/10 px-3 py-2 text-xs">VISA</span><span class="rounded bg-white/10 px-3 py-2 text-xs">UPI</span><span class="rounded bg-white/10 px-3 py-2 text-xs">PAY</span></div></div></div><div class="border-t border-white/10"><div class="mx-auto flex max-w-[1320px] flex-col gap-2 px-4 py-5 text-xs text-slate-500 sm:flex-row sm:justify-between sm:px-6"><span>© {{ date('Y') }} MyCart. All rights reserved.</span><span>Secure payments · Fast shipping · Easy returns</span></div></div></footer>
</body>
</html>
